name: autoupdate
on:
  push:
    branches:
      - master

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_MSG: "Branch was auto-updated."
          RETRY_COUNT: "1"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "fail"
